### ISSUE TITLE
Conflict between pytorch and scar because of setuptools

### ISSUE THREAD

**Issue by recursivelymanan** [Novartis/scar#72]
Hello! Thanks for your help with my previous issue! I was able to successfully run `scar.model()` with `device='cpu'`, but as expected it was somewhat slow. However, I am unable to utilize `device='cuda'` because `pytorch-cuda12.1` requires `setuptools=70.0.0`, while it seems like `scar` requires `setuptools<59.5.0`. I also ran into some confusing dependency issues, because it seems like `setuptools=59.5` is not supported for `python>=3.10`.

Is the issue just on my end? Admittedly I may just be missing something obvious about the installation, but as a sanity check I downloaded `pytorch` in a clean environment without `scar` and it was able to successfully detect my gpu. However, in an environment with scar it is unable to detect. 

Any guidance would be appreciated, and my apologies if this is out of the scope of this package.

**Comment by CaibinSh** [comment]
Hi @recursivelymanan , thanks very much again for identifying this issue.

We have now required setuptools>=68.1.2 instead of setuptools>=42. It should work now with git clone + pip installation.

**Comment by CaibinSh** [comment]
Hi @recursivelymanan ,

conda install also works. 

```
conda create -n scar python=3.10.*
conda activate scar
conda install bioconda::scar
```

**Comment by recursivelymanan** [comment]
I'm still getting this message when I try to install `scar` with `mamba install bioconda::scar=0.5.5`:

```
Encountered problems while solving:
  - package scar-0.5.5-pyhdfd78af_0 requires setuptools <=59.5.0, but none of the providers can be installed
```

This happens after installing pytorch, which installs `setuptools=70.0.0`.

**Comment by CaibinSh** [comment]
Hi @recursivelymanan , thanks again. I have updated the conda dependency as well as the instruction on installation, please check it out here,

https://scar-tutorials.readthedocs.io/en/main/Installation.html

I tested it and it worked. Please do not hesitate to let me know if there are any issues.
